code --install-extension adpyke.codesnap &&
code --install-extension bradlc.vscode-tailwindcss &&
code --install-extension christian-kohler.path-intellisense &&
code --install-extension dbaeumer.vscode-eslint &&
code --install-extension drcika.apc-extension &&
code --install-extension eamodio.gitlens &&
code --install-extension ecmel.vscode-html-css &&
code --install-extension gencer.html-slim-scss-css-class-completion &&
code --install-extension JakeBecker.elixir-ls &&
code --install-extension jock.svg &&
code --install-extension miguelsolorio.symbols &&
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR &&
code --install-extension ms-vscode.vscode-typescript-next &&
code --install-extension naumovs.color-highlight &&
code --install-extension phoenixframework.phoenix &&
code --install-extension shd101wyy.markdown-preview-enhanced &&
code --install-extension SimonSiefke.svg-preview &&
code --install-extension Siris01.catppuccin-theme &&
code --install-extension stringham.move-ts &&
code --install-extension syler.sass-indented &&
code --install-extension usernamehw.errorlens &&
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples &&
code --install-extension VisualStudioExptTeam.vscodeintellicode
